// Code generated by tygo. DO NOT EDIT.

//////////
// source: sdk_app.go

export interface AppSDKTypes {
}

//////////
// source: usage.go

/**
 * MetaItemType is the type discriminator for MetaItem
 */
export type MetaItemType = string;
export const MetaItemTypeText: MetaItemType = "text";
export const MetaItemTypeImage: MetaItemType = "image";
export const MetaItemTypeVideo: MetaItemType = "video";
export const MetaItemTypeAudio: MetaItemType = "audio";
export const MetaItemTypeRaw: MetaItemType = "raw";
/**
 * VideoResolution represents standard video resolution presets
 */
export type VideoResolution = string;
export const VideoRes480P: VideoResolution = "480p";
export const VideoRes720P: VideoResolution = "720p";
export const VideoRes1080P: VideoResolution = "1080p";
export const VideoRes1440P: VideoResolution = "1440p";
export const VideoRes4K: VideoResolution = "4k";
/**
 * MetaItem represents metadata about an input or output item
 */
export interface MetaItem {
  type: MetaItemType;
  /**
   * Text fields
   */
  tokens?: number /* int */;
  /**
   * Image/Video shared fields
   */
  width?: number /* int */;
  height?: number /* int */;
  resolution_mp?: number /* float64 */;
  /**
   * Image specific fields
   */
  steps?: number /* int */;
  count?: number /* int */;
  /**
   * Video specific fields
   */
  resolution?: VideoResolution;
  seconds?: number /* float64 */;
  fps?: number /* int */;
  /**
   * Audio specific fields
   */
  sample_rate?: number /* int */;
  /**
   * Raw specific fields
   */
  cost?: number /* float64 */; // Cost in dollar cents (for raw/passthrough pricing)
  /**
   * App-specific key-value pairs for custom pricing factors
   */
  extra?: { [key: string]: any};
}
/**
 * OutputMeta contains structured metadata about task inputs and outputs for pricing calculation
 */
export interface OutputMeta {
  inputs: MetaItem[];
  outputs: MetaItem[];
}
