// Code generated by gotypegen. DO NOT EDIT.

//////////
// source: models.go

/**
 * RequestMetadata is the metadata envelope carried in both directions:
 * engine -> worker on /setup and /run, and worker -> engine API on callbacks.
 */
export interface RequestMetadata {
  worker_id: string;
  app_id: string;
  app_version_id: string;
  app_variant: string;
  gpu_ids: string[];
  task_id: string;
  team_id: string;
  user_id: string;
}
export interface AppSDKTypes {
}
/**
 * MetaItem represents metadata about an input or output item
 */
export interface MetaItem {
  type: MetaItemType;
  tokens?: number /* int */;
  width?: number /* int */;
  height?: number /* int */;
  resolution_mp?: number /* float64 */;
  steps?: number /* int */;
  count?: number /* int */;
  resolution?: VideoResolution;
  seconds?: number /* float64 */;
  fps?: number /* int */;
  sample_rate?: number /* int */;
  cost?: number /* float64 */;
  extra?: { [key: string]: any};
}
/**
 * OutputMeta contains structured metadata about task inputs and outputs for pricing calculation
 */
export interface OutputMeta {
  inputs: MetaItem[];
  outputs: MetaItem[];
}
/**
 * MetaItemType is the type discriminator for MetaItem
 */
export type MetaItemType = string;
export const MetaItemTypeText: MetaItemType = "text";
export const MetaItemTypeImage: MetaItemType = "image";
export const MetaItemTypeVideo: MetaItemType = "video";
export const MetaItemTypeAudio: MetaItemType = "audio";
export const MetaItemTypeRaw: MetaItemType = "raw";
/**
 * VideoResolution represents standard video resolution presets
 */
export type VideoResolution = string;
export const VideoRes480P: VideoResolution = "480p";
export const VideoRes720P: VideoResolution = "720p";
export const VideoRes1080P: VideoResolution = "1080p";
export const VideoRes1440P: VideoResolution = "1440p";
export const VideoRes4K: VideoResolution = "4k";
